SELECT C.CAR_MAKE AS CAR
FROM CARS C, CAR_USERS U, ID_CAR_USERS_ID_CARS I
WHERE C.ID = I.ID_CAR AND I.ID_CAR_USER = U.ID
	AND U.CITY = 'Казань'

SELECT U.U_NAME AS USERNAME
FROM CAR_USERS U, ID_CAR_USERS_ID_CARS I
WHERE EXISTS (SELECT *
		FROM CARS C
		WHERE C.ID = I.ID_CAR AND I.ID_CAR_USER = U.ID
			AND C.MILEAGE > 100);

SELECT U.U_NAME AS USERNAME, C.CAR_MAKE AS CAR
FROM CAR_USERS U, CARS C, ID_CAR_USERS_ID_CARS I
WHERE U.ID = I.ID_CAR_USER AND I.ID_CAR = C.ID
	AND C.MILEAGE > 50 AND U.AGE > 20

