CREATE TABLE CAR_USERS (
ID SERIAL PRIMARY KEY,
U_NAME VARCHAR(50) NOT NULL,
AGE INT NOT NULL,
U_PASSWORD VARCHAR(100) NOT NULL,
CITY VARCHAR(50) NOT NULL
);

CREATE TABLE CARS (
ID SERIAL PRIMARY KEY,
CAR_MAKE VARCHAR(100) NOT NULL,
MILEAGE INT NOT NULL,
POWER INT NOT NULL
);

CREATE TABLE ID_CAR_USERS_ID_CARS (
ID SERIAL PRIMARY KEY,
ID_CAR_USER INT NOT NULL,
ID_CAR INT NOT NULL,
FOREIGN KEY (ID_CAR_USER) REFERENCES CAR_USERS (ID),
FOREIGN KEY (ID_CAR) REFERENCES CARS (ID)
);