INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Александр', 37, 'qwerty001', 'Москва');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Борис', 56, 'qwerty024', 'Екатеринбург');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Виталий', 25, 'qwerty032', 'Казань');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Глеб', 19, 'qwerty021', 'Минск');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Дмитрий', 31, 'qwerty313', 'Самара');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Егор', 53, 'qwerty214', 'Москва');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Жозеф', 48, 'qwerty225', 'Париж');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Захар', 63, 'qwerty102', 'Владивосток');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Иннокентий', 59, 'qwerty570', 'Воронеж');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Кирилл', 24, 'qwerty362', 'Казань');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Леонид', 42, 'qwerty843', 'Сочи');
INSERT INTO CAR_USERS (U_NAME, AGE, U_PASSWORD, CITY)
VALUES ('Марат', 35, 'qwerty732', 'Казань');


INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Audi', 21, 180);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('BMW', 53, 213);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Ford', 321, 92);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Honda', 0, 103);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Hyundai', 213, 78);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Kia', 32, 83);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Lada', 19, 60);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Mazda', 0, 108);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Mercedes-Benz', 0, 171);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Mitsubishi', 342, 289);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Nissan', 12, 243);
INSERT INTO CARS (CAR_MAKE, MILEAGE, POWER)
VALUES ('Renault', 42, 94);

INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (1, 1);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (6, 5);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (1, 8);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (2, 2);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (9, 7);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (7, 12);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (5, 6);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (12, 9);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (3, 4);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (12, 11);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (10, 10);
INSERT INTO ID_CAR_USERS_ID_CARS (ID_CAR_USER, ID_CAR)
VALUES (6, 4);
  